### ISSUE TITLE
share code

### ISSUE THREAD

**Issue by shizicdj** [zhaohaojie1998/DRL-for-Path-Planning#1]

**Comment by shizicdj** [comment]
@zhaohaojie1998 Sorry to bother you，brother！

**Comment by shizicdj** [comment]
Hello! @zhaohaojie1998 I hope this message finds you well. I've been trying to replicate the style of your `train_static.py` by creating a `train_dynamic.py` `script.` However, when attempting to train the LIDAR obstacle avoidance model, I encountered the following error:

```plaintext
Traceback (most recent call last):
  File "E:\Study\Recognition\DRL-for-Path-Planning\train_dynamic.py", line 30, in <module>
    agent = SAC(env.observation_space, env.action_space, memory_size=10000) # Instantiate reinforcement learning algorithm
  File "E:\Study\Recognition\DRL-for-Path-Planning\sac.py", line 267, in __init__
    self.buffer = EasyBuffer(self.memory_size, self.observation_space, self.action_space)
  File "E:\Study\Recognition\DRL-for-Path-Planning\sac.py", line 134, in __init__
    assert not isinstance(obs_space, (gym.spaces.Tuple, gym.spaces.Dict)), "Truncated version of the buffer only supports simple data"
AssertionError: The truncated buffer only supports simple data
```

This issue prevents me from reproducing the fantastic results shown in the dynamic example images you provided. Could you please guide me on how to resolve this problem? Additionally, could you share the code for training the LIDAR obstacle avoidance model?

I assure you that I will adhere to academic ethics in using and learning from your code. Thank you for your assistance!

**Comment by shizicdj** [comment]
Hello! @zhaohaojie1998 ! I hope this message finds you well. I've been trying to replicate the style of your `train_static.py` by creating a `train_dynamic.py` script. However, when attempting to train the LIDAR obstacle avoidance model, I encountered the following error:

```plaintext
Traceback (most recent call last):
  File "E:\Study\Recognition\DRL-for-Path-Planning\train_dynamic.py", line 30, in <module>
    agent = SAC(env.observation_space, env.action_space, memory_size=10000) # 实例化强化学习算法
  File "E:\Study\Recognition\DRL-for-Path-Planning\sac.py", line 267, in __init__
    self.buffer = EasyBuffer(self.memory_size, self.observation_space, self.action_space)
  File "E:\Study\Recognition\DRL-for-Path-Planning\sac.py", line 134, in __init__
    assert not isinstance(obs_space, (gym.spaces.Tuple, gym.spaces.Dict)), "阉割版缓存只能存简单数据"
AssertionError: 阉割版缓存只能存简单数据
```

This issue prevents me from reproducing the fantastic results shown in the dynamic example images you provided. Could you please guide me on how to resolve this problem? Additionally, could you share the code for training the LIDAR obstacle avoidance model?

I assure you that I will adhere to academic ethics in using and learning from your code. Thank you for your assistance!

**Comment by shizicdj** [comment]
Hello! @zhaohaojie1998 ! I hope this message finds you well. I've been trying to replicate the style of your train_static.py by creating a train_dynamic.py script. However, when attempting to train the LIDAR obstacle avoidance model, I encountered the following error:

Traceback (most recent call last):
  File "E:\Study\Recognition\DRL-for-Path-Planning\train_dynamic.py", line 30, in <module>
    agent = SAC(env.observation_space, env.action_space, memory_size=10000) # 实例化强化学习算法
  File "E:\Study\Recognition\DRL-for-Path-Planning\sac.py", line 267, in __init__
    self.buffer = EasyBuffer(self.memory_size, self.observation_space, self.action_space)
  File "E:\Study\Recognition\DRL-for-Path-Planning\sac.py", line 134, in __init__
    assert not isinstance(obs_space, (gym.spaces.Tuple, gym.spaces.Dict)), "阉割版缓存只能存简单数据"
AssertionError: 阉割版缓存只能存简单数据

I have been struggling with this for three days without any progress. This issue prevents me from reproducing the fantastic results shown in the dynamic example images you provided. Could you please guide me on how to resolve this problem? Additionally, could you share the code for training the LIDAR obstacle avoidance model?

I assure you that I will adhere to academic ethics in using and learning from your code. Thank you for your assistance!

**Comment by shizicdj** [comment]
Hello! @zhaohaojie1998 ! I hope this message finds you well. I've been trying to replicate the style of your `train_static.py` by creating a `train_dynamic.py` script. However, when attempting to train the LIDAR obstacle avoidance model, I encountered the following error:
```
Traceback (most recent call last):
File "E:\Study\Recognition\DRL-for-Path-Planning\train_dynamic.py", line 30, in
agent = SAC(env.observation_space, env.action_space, memory_size=10000) # 实例化强化学习算法
File "E:\Study\Recognition\DRL-for-Path-Planning\sac.py", line 267, in init
self.buffer = EasyBuffer(self.memory_size, self.observation_space, self.action_space)
File "E:\Study\Recognition\DRL-for-Path-Planning\sac.py", line 134, in init
assert not isinstance(obs_space, (gym.spaces.Tuple, gym.spaces.Dict)), "阉割版缓存只能存简单数据"
AssertionError: 阉割版缓存只能存简单数据
```

I have been struggling with this for three days without any progress. This issue prevents me from reproducing the fantastic results shown in the dynamic example images you provided. Could you please guide me on how to resolve this problem? Additionally, could you share the code for training the LIDAR obstacle avoidance model?

I assure you that I will adhere to academic ethics in using and learning from your code. Thank you for your assistance!
